config/routes.rb
CouchbaseTinyurl::Application.routes.draw do
  resources :links do
    get :short, :on => :member
    get :my, :on => :collection
    get :recent, :on => :collection
    get :popular, :on => :collection
  end
  root :to => 'links#my'
  match "/:id", :to => 'links#short', :as => :short
end

app/models/couch.rb
module Couch

  class << self

    def domain
      return "http://#{ENV['COUCHBASE_DOMAIN']}" if ENV['COUCHBASE_DOMAIN']
      case Rails.env.to_s
        when "production"  then "http://localhost"
        when "test"        then "http://localhost"
        when "development" then "http://localhost"
      end
    end

    def client
      @client ||= Couchbase.new "#{domain}:8091/pools/default"
    end

  end

end

app/models/link.rb
class Link

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Callbacks
  extend ActiveModel::Naming

  attr_accessor :url, :key, :views, :session_id, :created_at
  @@keys = [:url, :key, :views, :session_id, :created_at]

  define_model_callbacks :save
  validates :url, :presence => true, :url => {:allow_nil => true, :message => "This is not a valid URL"}
  before_save :generate_key

  def generate_key
    while self.key.nil?
      random = SecureRandom.hex(2)
      self.key = random if self.class.find(random).nil?
    end
  end

  # ActiveModel

  def initialize(attributes = {})
    @errors = ActiveModel::Errors.new(self)
    attributes.each do |name, value|
      next unless @@keys.include?(name.to_sym)
      send("#{name}=", value)
    end
    self.views ||= 0
    self.created_at ||= Time.zone.now
  end

  def to_param
    self.key
  end

  def persisted?
    return false unless (key && valid?)
    # TODO need a better way to track if an object is *dirty* or not...
    self.class.find(key).url == self.url
  end

  def save
    return false unless valid?
    run_callbacks :save do
      # TODO should client.set return nil if sucessful? don't think so
      Couch.client.set(self.key, {
        :type => self.class.to_s.downcase,
        :url => self.url,
        :key => self.key,
        :views => self.views,
        :session_id => self.session_id,
        :created_at => self.created_at
      })
    end
    true
  end

  def self.find(key)
    return nil unless key
    begin
      doc = Couch.client.get(key)
      self.new(doc)
    rescue Memcached::NotFound => e
      nil
    end
  end

  # Couchbase Views

  def self.design
    @@design ||= Couch.client.design_docs['link']
  end

  @@design_doc = {
    'by_view_count' => {
      'map' => 'function(doc){ if(doc.type == "link"){ emit(doc.views, doc); }}',
    },
    'by_session_id' => {
      'map' => 'function(doc){ if(doc.type == "link" && doc.session_id != null){ emit(doc.session_id, doc); }}',
    },
    'by_created_at' => {
      'map' => 'function(doc){ if(doc.type == "link" && doc.created_at != null){ emit(doc.created_at, doc); }}',
    }
  }

  if Couch.client.design_docs.include?("link")
    Couch.client.delete_design_doc('link')
    Couch.client.save_design_doc('link', @@design_doc)
  else
    Couch.client.save_design_doc('link', @@design_doc)
  end

  def self.popular
    results = design.by_view_count(:descending => true).entries
    results.map { |result| new(result['value']) }
  end

  def self.by_session_id(session_id)
    results = design.by_session_id(:key => session_id).entries
    results.map { |result| new(result['value']) }
  end

  def self.recent
    results = design.by_created_at(:descending => true).entries
    results.map { |result| new(result['value']) }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def create
    @link = Link.new(params[:link])
    @link.session_id = session[:session_id]
    if @link.save
      respond_to do |format|
        format.html { redirect_to @link }
        format.js   
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.js
      end
    end
  end

  def short
    @link = Link.find(params[:id])
    redirect_to root_path unless @link
    @link.views += 1
    @link.save
    redirect_to @link.url
  end

  def show
    @link = Link.find(params[:id])
  end
  
  def my
    @filter = "my_links"
    @filtered_links = Link.by_session_id(session[:session_id])
    @link = Link.new
  end
  
  def recent
    @filter = "recent"
    @filtered_links = Link.recent
    @link = Link.new
  end
  
  def popular
    @filter = "popular"
    @filtered_links = Link.popular
    @link = Link.new
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Squish - Couchbase URL Shortening Application</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <script type="text/javascript" src="http://use.typekit.com/dwa2mvc.js"></script>;
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container header-wrapper">
    <header class="header row">
      <hgroup>
        <h1><a href="/">Squish</a></h1>
        <h2>A Demo Rails URL shortening application using <%= link_to "Couchbase", "http://couchbase.org" %></h2>
      </hgroup>
    </header>
  </div>
  
  <div class="full-width squish-wrapper">
    <div class="container">
        <%= render :partial => "links/form" %>
    </div>
  </div>
  <div class="container">
    <ul class="link-nav <%= " #{@filter}" %>">
      <li><%= link_to "My Squishes", my_links_path, {:class => "my_links", :remote => true} %></li>
      <li><%= link_to "Recently Squished", recent_links_path, {:class => "recent", :remote => true} %></li>
      <li><%= link_to "Popular Squishes", popular_links_path, {:class => "popular", :remote => true} %></li>
    </ul>

    <%= yield %>
  
  </div>

  <div class="full-width footer-wrapper">
    <footer class="container">
      <p>A <a href="http://rumblelabs.com">Rumble Labs</a> Creation</p>
      <a id="github" href="https://github.com/rumblelabs/couchbase-tinyurl">
        <span>Fork Squish on GitHub</span>
      </a>
    </footer>
  </div>
</body>
</html>

app/views/links/_form.html.erb
<%- if @link.errors.any? -%>
  <%- @link.errors.each do |field, message| -%>
    <strong><%= field.to_s.upcase %></strong> <%= message %>.
  <%- end -%>
<%- end -%>
<%= form_for @link, :remote => true do |f| %>
  <input type="text" name="link[url]" id="id_url" placeholder="Enter your URL…"/>
  <%= f.submit "Squish It" %>
<%- end -%>

app/views/links/_link.html.erb
<tr>
  <td class="short-url"><%= link_to short_url(link.key), short_url(link.key) %></td>
  <td class="long-url"><%= link_to(truncate(link.url, :length => 64), link.url) %></td>
  <td class="num-views"><span><%= link.views %></span></td>
  <td class="time-since"><%= distance_of_time_in_words link.created_at, Time.zone.now %></td>
</tr>

app/views/links/_links.html.erb
<table class="link-table" id="link-table">
  <thead>
    <th width="200px">Squished Link</th>
    <th width="400px">Long Link</th>
    <th width="70px">Views</th>
    <th width="70px">When</th>
  </thead>
  <tbody>
    <%= render links %>
  </tbody>
</table>

app/views/links/_short_url.html.erb
<div class="short-link-container">
  <label>Squished</label>
  <input type="text" readonly="readonly" value="<%= "#{short_url(@link)}" %>"/>
</div>

app/views/links/create.js.erb
<%- if(@link.valid?) -%>
  $('.short-link-container, .error').remove();
  $('#new_link').after("<%= escape_javascript(render(:partial => "short_url")) %>");
  $('.link-table').prepend("<%= escape_javascript(render(:partial => "link", :locals => { :link => @link })) %>");
  $('.short-link-container input').focus().select();
<%- else -%>
  <%- @link.errors.each do |field, message| -%>
    $('#new_link').after('<div class="error"><%= escape_javascript(message) %></div>');
  <%- end -%>
  
<%- end -%>

app/views/links/my.html.erb
<%= render 'links', :links => @filtered_links %>

app/views/links/my.js.erb
$('.link-table').html("<%= escape_javascript(render(:partial => "links", :locals => { :links => @filtered_links })) %>");
$('.link-nav').removeClass().addClass('my_links link-nav');

app/views/links/new.html.erb
<div class="row">
<%= render :partial => "form" %>
</div>

app/views/links/popular.html.erb
<%= render 'links', :links => @filtered_links %>

app/views/links/popular.js.erb
$('.link-table').html("<%= escape_javascript(render(:partial => "links", :locals => { :links => @filtered_links })) %>");
$('.link-nav').removeClass().addClass('popular link-nav');

app/views/links/recent.html.erb
<%= render 'links', :links => @filtered_links %>

app/views/links/recent.js.erb
$('.link-table').html("<%= escape_javascript(render(:partial => "links", :locals => { :links => @filtered_links })) %>");
$('.link-nav').removeClass().addClass('recent link-nav');